local M = {}

M.sections = {
  {
    category = "Leader Key",
    items = {
      "<Space>                → Leader key",
    },
  },
  {
    category = "Standard Vim Bindings",
    items = {
      "## Normal Mode",
      "h/j/k/l               → Move cursor (←↓↑→)",
      "w/b                   → Move to next/previous word",
      "0/$                   → Move to start/end of line",
      "gg/G                  → Go to first/last line",
      ":n                    → Go to line n",
      "u                     → Undo",
      "<C-r>                 → Redo",
      "yy                    → Yank (copy) line",
      "p/P                   → Paste after/before cursor",
      "dd                    → Delete (cut) line",
      "x                     → Delete character under cursor",
      "i/a                   → Enter insert mode before/after cursor",
      "o/O                   → Open new line below/above",
      ":s/pattern/repl/g     → Substitute in line",
      ":%s/pattern/repl/g    → Substitute in file",
      "/                     → Search forward",
      "?                     → Search backward",
      "n/N                   → Next/previous search match",
      "*                     → Search word under cursor forward",
      "#                     → Search word under cursor backward",
      "cgn                   → Change next search match, repeatable",
      ":q                    → Quit",
      ":w                    → Save",
      ":wq                   → Save and quit",
      ":qa                   → Quit all",
      "<Ctrl-c>              → Interrupt command",
      "zz                    → Center cursor on screen",
      "zt/zb                 → Scroll to top/bottom",
      "zo/zc                 → Open/close fold",
      "zR/zM                 → Open/close all folds",
      "za                    → Toggle fold under cursor",
      "## Visual Mode",
      "v                     → Enter visual mode",
      "V                     → Enter linewise visual mode",
      "<C-v>                 → Enter blockwise visual mode",
      "y                     → Yank selection",
      "d                     → Delete selection",
      "p/P                   → Paste after/before, replacing selection",
      ">/<                   → Indent/outdent selection",
      "~                     → Toggle case of selection",
      "## Insert Mode",
      "<C-h>                 → Delete character before cursor",
      "<C-w>                 → Delete word before cursor",
      "<C-u>                 → Delete to start of line",
      "<Esc>                 → Exit to normal mode",
      "## Macros (Recordings)",
      "qa..z                 → Record macro into register a..z",
      "@a..z                 → Replay macro from register a..z",
      "@@                    → Replay last macro",
      "## Registers",
      "\"ayy                  → Yank line to register a",
      "\"ap                   → Paste from register a",
      "\"ay                   → Yank selection to register a (visual)",
      ":reg                  → Show register contents",
      "\"0p                   → Paste from yank register",
      "\"+p                   → Paste from system clipboard",
      "\"_d                   → Delete to black hole register",
      "## Command Line",
      ":                     → Enter command-line mode",
      "<C-c>                 → Cancel command",
      "<C-p>/<C-n>           → Cycle previous/next command history",
      "## Text Objects",
      "iw                    → Inner word",
      "aw                    → Around word",
      "i\"/i'/i`              → Inner quotes (double/single/backtick)",
      "a\"/a'/a`              → Around quotes",
      "i(/i[/i{              → Inner parentheses/brackets/braces",
      "a(/a[/a{              → Around parentheses/brackets/braces",
      "it                    → Inner tag (HTML/XML)",
      "at                    → Around tag",
      "ciw/diw/yiwo          → Change/delete/yank inner word",
      "ci\"/di\"/yi\"           → Change/delete/yank inner quotes",
      "ci(/di(/yi(          → Change/delete/yank inner parentheses",
    },
  },
  {
    category = "Core Neovim (Normal Mode)",
    items = {
      "n: <CR>               → Disabled",
      "n: <leader>+          → Increase font size",
      "n: J                  → Join lines, keep cursor",
      "n: <C-d>              → Scroll down half page, center",
      "n: <C-u>              → Scroll up half page, center",
      "n: n                  → Next search, center, reselect",
      "n: N                  → Prev search, center, reselect",
      "n: Q                  → Disabled",
      "n: <leader>f          → Format buffer (LSP)",
      "n: <leader>s          → Substitute word under cursor (case-insensitive)",
      "n: <leader>S          → Substitute word under cursor (case-sensitive)",
      "n: <leader>x          → Make file executable",
      "n: <leader><leader>   → Source file (or TypeAnim in netrw)",
      "n: <C-a>              → Select all",
      "n: <esc>              → Clear search highlight",
    },
  },
  {
    category = "Core Neovim (Visual Mode)",
    items = {
      "v: J                  → Move selected block down",
      "v: K                  → Move selected block up",
      "x: <leader>p          → Replace selection with yanked text",
      "v: <leader>y          → Copy to system clipboard",
      "n: <leader>Y          → Yank to end of line to clipboard",
      "v: <leader>d          → Delete without affecting clipboard",
    },
  },
  {
    category = "Core Neovim (Insert Mode)",
    items = {
      "i: <C-c>              → Exit to normal mode",
    },
  },
  {
    category = "Core Neovim (Help Files)",
    items = {
      "h: <CR>               → Jump to tag under cursor",
    },
  },
  {
    category = "Terminal Integration (Normal Mode)",
    items = {
      "n: <leader>t          → Open terminal in split",
      "n: <C-t>              → Toggle floating terminal",
      "n: <leader>th         → Move to terminal left",
      "n: <leader>tj         → Move to terminal down",
      "n: <leader>tk         → Move to terminal up",
      "n: <leader>tl         → Move to terminal right",
    },
  },
  {
    category = "Tab Management (Normal Mode)",
    items = {
      "n: <leader>tn         → New tab",
      "n: <leader>tc         → Close tab",
      "n: <leader>tl         → Next tab",
      "n: <leader>th         → Previous tab",
      "n: gt                 → Next tab",
      "n: gT                 → Previous tab",
    },
  },
  {
    category = "Buffer Management (Normal Mode)",
    items = {
      "n: <leader>bl         → List buffers (:ls or Telescope)",
      "n: <leader>bn         → Next buffer (:bnext)",
      "n: <leader>bp         → Previous buffer (:bprev)",
      "n: <leader>bd         → Delete buffer (:bd)",
      "n: <leader>bf         → First buffer (:bfirst)",
      "n: <leader>bb         → Last buffer (:blast)",
    },
  },
  {
    category = "Folding (Normal Mode)",
    items = {
      "n: zo                 → Open fold under cursor",
      "n: zc                 → Close fold under cursor",
      "n: zR                 → Open all folds",
      "n: zM                 → Close all folds",
      "n: za                 → Toggle fold under cursor",
    },
  },
  {
    category = "File Explorer (NvimTree, Normal Mode)",
    items = {
      "n: <leader>pv         → Toggle NvimTree",
    },
  },
  {
    category = "Window Management (Normal Mode)",
    items = {
      "n: <leader>-          → Split window horizontal",
      "n: <leader>|          → Split window vertical",
      "n: sh                 → Move to window left",
      "n: sj                 → Move to window down",
      "n: sk                 → Move to window up",
      "n: sl                 → Move to window right",
      "n: Sh                 → Move window to far left",
      "n: Sj                 → Move window to bottom",
      "n: Sk                 → Move window to top",
      "n: Sl                 → Move window to far right",
      "n: <C-left>           → Resize window narrower",
      "n: <C-right>          → Resize window wider",
      "n: <C-up>             → Resize window taller",
      "n: <C-down>           → Resize window shorter",
    },
  },
  {
    category = "Quickfix and Location Lists (Normal Mode)",
    items = {
      "n: <C-k>              → Next quickfix item, center",
      "n: <C-j>              → Prev quickfix item, center",
      "n: <leader>k          → Next location list item, center",
      "n: <leader>j          → Prev location list item, center",
      "n: <leader>q          → Open diagnostics location list",
      "n: <leader>dq         → Diagnostics → quickfix list + open",
    },
  },
  {
    category = "Diagnostics (Normal Mode)",
    items = {
      "n: <leader>dn         → Next diagnostic",
      "n: <leader>dp         → Previous diagnostic",
      "n: <leader>de         → Show diagnostic float (or goto next)",
      "n: <leader>dg         → Diagnostic settings picker",
    },
  },
  {
    category = "Completion (nvim-cmp, Insert Mode)",
    items = {
      "i: <C-b>              → Scroll docs up",
      "i: <C-f>              → Scroll docs down",
      "i: <C-Space>          → Trigger completion",
      "i: <C-e>              → Abort completion",
      "i: <CR>               → Confirm completion",
      "i: <Tab>              → Select next item",
      "i: <S-Tab>            → Select previous item",
    },
  },
  {
    category = "Completion (nvim-cmp, Command Line)",
    items = {
      "c: /                  → Buffer completion in search",
      "c: :                  → Path and cmdline completion",
    },
  },
  {
    category = "Snippet Expansion (LuaSnip, Insert Mode)",
    items = {
      "i: <C-j>              → Expand snippet or jump to next placeholder",
      "i: <C-k>              → Jump to previous placeholder",
    },
  },
  {
    category = "Comment Toggling (Comment.nvim, Normal/Visual Mode)",
    items = {
      "n: gcc                → Toggle comment on line",
      "v: gc                 → Toggle comment on selection",
      "n: gco                → Add comment above",
      "n: gcA                → Add comment at end of line",
    },
  },
  {
    category = "Surround (vim-surround, Normal/Visual Mode)",
    items = {
      "n: ysiw\"/ysiw)        → Add quotes/parentheses around word",
      "n: cs\"'               → Change quotes to single quotes",
      "n: ds\"                → Delete quotes",
      "v: S\"                 → Surround selection with quotes",
      "n: yss\"               → Surround line with quotes",
    },
  },
  {
    category = "Multiple Cursors (vim-visual-multi, Normal Mode)",
    items = {
      "n: <C-n>              → Add cursor at next word",
      "n: <C-p>              → Add cursor at previous word",
      "n: <C-x>              → Skip and add next cursor",
      "n: <Tab>              → Toggle cursor mode",
    },
  },
  {
    category = "Harpoon (Normal Mode)",
    items = {
      "n: <leader>a          → Add file",
      "n: <C-e>              → Toggle menu",
      "n: <leader>1          → Jump to file 1",
      "n: <leader>2          → Jump to file 2",
      "n: <leader>3          → Jump to file 3",
      "n: <leader>4          → Jump to file 4",
    },
  },
  {
    category = "Fugitive (Git, Normal Mode)",
    items = {
      "n: <leader>gs         → Git status",
      "n: <leader>p          → Git push (fugitive buffer)",
      "n: <leader>r          → Git rebase -i (fugitive buffer)",
      "n: <leader>l          → Git log (10 commits, fugitive buffer)",
    },
  },
  {
    category = "Gitsigns (Git, Normal Mode)",
    items = {
      "n: ]h                 → Next hunk",
      "n: [h                 → Previous hunk",
      "n: <leader>hs         → Stage hunk",
      "n: <leader>hr         → Reset hunk",
      "n: <leader>hS         → Stage buffer",
      "n: <leader>hu         → Undo stage hunk",
      "n: <leader>hp         → Preview hunk",
      "n: <leader>hb         → Blame line",
      "n: <leader>hd         → Diff this",
      "n: <leader>tb         → Toggle current line blame",
      "n: ih                 → Select hunk (operator-pending)",
    },
  },
  {
    category = "Diffview (Git, Normal Mode)",
    items = {
      "n: <leader>gd         → Open diffview",
      "n: <leader>gh         → File history",
      "n: <leader>gm         → Diff with main branch",
    },
  },
  {
    category = "LSP (Normal Mode)",
    items = {
      "n: gr                 → Telescope lsp_references",
      "n: gd                 → Go to definition",
      "n: K                  → Hover",
      "n: <leader>rn         → Rename symbol",
      "n: <leader>ca         → Code action",
      "n: <leader>ws         → Workspace symbol",
      "n: <leader>lr         → Restart all LSP clients",
    },
  },
  {
    category = "LSP (Insert Mode)",
    items = {
      "i: <C-h>              → Signature help",
    },
  },
  {
    category = "DAP (Debugging, Normal Mode)",
    items = {
      "n: <leader>db         → Toggle breakpoint",
      "n: <leader>dc         → Continue",
      "n: <leader>ds         → Step over",
      "n: <leader>di         → Step into",
      "n: <leader>do         → Step out",
      "n: <leader>dt         → DAP UI: Toggle",
      "n: <leader>dr         → DAP UI: Reset",
    },
  },
  {
    category = "Diagnostic Picker (personal, Normal Mode)",
    items = {
      "n: <leader>dg         → Open picker (toggle LSP/clang-tidy checks)",
      "## Inside the picker",
      "j/k                   → Navigate items",
      "<Space>               → Toggle item / select radio option",
      "<Tab>                 → Expand/collapse a category",
      "<CR>                  → Write config and restart LSP",
      "<Esc>                 → Close without changes",
      "(type)                → Filter (collapsed categories searched too)",
    },
  },
  {
    category = "Devdocs (personal, offline manuals)",
    items = {
      "n: gK                 → Look up symbol under cursor (mapped filetypes)",
      "c: :Devdocs           → Fuzzy-browse every installed docset",
      "c: :Devdocs <query>   → Browse, pre-filtered",
      "c: :Devdocs <docset> [query] → Browse one docset",
      "c: :DevdocsUpdate [docset]   → Download + convert docsets",
      "c: :DevdocsNote       → Author a custom note for current page",
      "## Inside a doc page",
      "K / <C-]> / gK        → Follow the reference under the cursor",
    },
  },
  {
    category = "Telescope (Normal Mode)",
    items = {
      "n: <leader>ph         → Help tags",
      "n: <leader>pf         → Find files (fzf sorting)",
      "n: <leader>en         → Find files in config",
      "n: <leader>ep         → Find files in data/lazy",
      "n: <leader>mg         → Multi grep (pattern [  glob], e.g., \"TODO  *.lua\")",
    },
  },
  {
    category = "Trouble (Normal Mode)",
    items = {
      "n: <leader>tt         → Toggle diagnostics",
      "n: <leader>[d         → Next diagnostic",
      "n: ]d                 → Previous diagnostic",
    },
  },
  {
    category = "Obsidian (in vaults, Normal Mode)",
    items = {
      "n: gf                 → Follow link",
      "n: <leader>ch         → Toggle checkbox",
    },
  },
  {
    category = "TypeAnim (Normal Mode)",
    items = {
      "n: <Space>            → Toggle animation (netrw file selection)",
      "n: <C-C>              → Kill animation (netrw file selection)",
    },
  },
  {
    category = "Zen Mode (Normal Mode)",
    items = {
      "n: <leader>zz         → Toggle",
      "n: C-<left>           → Increase width",
      "n: C-<right>          → Decrease width",
    },
  },
  {
    category = "Cheatsheet (Normal Mode)",
    items = {
      "n: <leader>cs         → Open cheatsheet",
    },
  },
  {
    category = "99 (AI, Normal/Visual Mode)",
    items = {
      "v: <leader>9v         → Visual prompt (selection)",
      "n: <leader>9x         → Stop all requests",
      "n: <leader>9s         → Search",
      "n: <leader>9m         → Select model",
      "n: <leader>9p         → Select provider",
    },
  },
  {
    category = "Mason",
    items = {
      "n: <leader>ms         → Open Mason UI (:Mason)",
    },
  },
  {
    category = "Table Mode (Markdown, Normal Mode)",
    items = {
      "n: <leader>tm         → Toggle table mode",
      "n: <leader>tt         → Create table",
      "i: ||                 → Start table",
      "n: <leader>tr         → Realign table",
    },
  },
}

return M
